"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dim = dim;
exports.combinations = combinations;
exports.generateFaces = generateFaces;
exports.getFacesLazy = getFacesLazy;
const hash_1 = require("./hash");
const normalize_1 = require("./normalize");
const types_1 = require("./types");
function dim(simplex) {
    return simplex.nodes.length - 1;
}
function* combinations(arr, k) {
    if (k === 0) {
        yield [];
        return;
    }
    for (let i = 0; i <= arr.length - k; i++) {
        for (const rest of combinations(arr.slice(i + 1), k - 1)) {
            yield [arr[i], ...rest];
        }
    }
}
function generateFaces(complex, simplex) {
    const simplexDim = dim(simplex);
    if (simplexDim > types_1.MAX_FACE_GEN_DIM) {
        console.warn(`[Simplicial] Simplex dim=${simplexDim} exceeds cap. Faces not auto-generated.`);
        return;
    }
    if (simplexDim === types_1.MAX_FACE_GEN_DIM) {
        return;
    }
    const nodes = (0, normalize_1.normalizeNodes)(simplex.nodes);
    for (let size = 2; size < nodes.length; size++) {
        for (const subset of combinations(nodes, size)) {
            const key = (0, normalize_1.normalizeKey)(subset);
            if (complex.simplices.has(key))
                continue;
            complex.simplices.set(key, {
                nodes: (0, normalize_1.normalizeNodes)(subset),
                autoGenerated: true,
                userDefined: false,
                parentKey: (0, normalize_1.normalizeKey)(simplex.nodes),
                colorKey: simplex.colorKey ?? (0, hash_1.hashLabel)(simplex.label),
            });
        }
    }
}
function getFacesLazy(simplex, targetDim) {
    return [...combinations(simplex.nodes, targetDim + 1)];
}
