"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimplicialModel = void 0;
const faces_1 = require("./faces");
const hash_1 = require("./hash");
const normalize_1 = require("./normalize");
const betti_1 = require("./betti");
function randomInRange(min, max) {
    return min + Math.random() * (max - min);
}
function randomBorderPosition(width, height, padding) {
    const halfWidth = width / 2;
    const halfHeight = height / 2;
    const usableHalfWidth = Math.max(padding + 40, halfWidth - padding);
    const usableHalfHeight = Math.max(padding + 40, halfHeight - padding);
    const side = Math.floor(Math.random() * 4);
    switch (side) {
        case 0:
            return {
                px: randomInRange(-usableHalfWidth, usableHalfWidth),
                py: -usableHalfHeight,
            };
        case 1:
            return {
                px: usableHalfWidth,
                py: randomInRange(-usableHalfHeight, usableHalfHeight),
            };
        case 2:
            return {
                px: randomInRange(-usableHalfWidth, usableHalfWidth),
                py: usableHalfHeight,
            };
        default:
            return {
                px: -usableHalfWidth,
                py: randomInRange(-usableHalfHeight, usableHalfHeight),
            };
    }
}
function createNode(id, bounds, isVirtual = false) {
    const width = bounds?.width ?? 960;
    const height = bounds?.height ?? 640;
    const { px, py } = randomBorderPosition(width, height, 80);
    return {
        id,
        px,
        py,
        vx: 0,
        vy: 0,
        isVirtual,
        isPinned: false,
        displayAlpha: 1,
    };
}
class SimplicialModel {
    constructor() {
        this.nodes = new Map();
        this.simplices = new Map();
        this.listeners = new Set();
        this.batchDepth = 0;
        this.hasPendingEmit = false;
    }
    subscribe(listener) {
        this.listeners.add(listener);
        return () => this.listeners.delete(listener);
    }
    emitChange() {
        if (this.batchDepth > 0) {
            this.hasPendingEmit = true;
            return;
        }
        this.flushChange();
    }
    flushChange() {
        this.listeners.forEach((listener) => listener());
    }
    batch(fn) {
        this.batchDepth++;
        try {
            return fn();
        }
        finally {
            this.batchDepth--;
            if (this.batchDepth === 0 && this.hasPendingEmit) {
                this.hasPendingEmit = false;
                this.flushChange();
            }
        }
    }
    setNode(id, opts) {
        const existing = this.nodes.get(id);
        if (existing) {
            Object.assign(existing, opts ?? {});
            if (opts?.isVirtual === false)
                existing.isVirtual = false;
            this.emitChange();
            return;
        }
        const node = createNode(id, undefined, opts?.isVirtual ?? false);
        if (opts?.px !== undefined)
            node.px = opts.px;
        if (opts?.py !== undefined)
            node.py = opts.py;
        if (opts?.isPinned !== undefined)
            node.isPinned = opts.isPinned;
        this.nodes.set(id, node);
        this.emitChange();
    }
    removeNode(id) {
        this.nodes.delete(id);
        for (const [key, simplex] of [...this.simplices]) {
            if (!simplex.nodes.includes(id))
                continue;
            this.simplices.delete(key);
        }
        this.emitChange();
    }
    updateNodeId(oldId, newId) {
        if (oldId === newId)
            return;
        const existing = this.nodes.get(oldId);
        if (existing) {
            this.nodes.set(newId, { ...existing, id: newId });
            this.nodes.delete(oldId);
        }
        for (const [key, simplex] of [...this.simplices]) {
            if (!simplex.nodes.includes(oldId))
                continue;
            const updated = {
                ...simplex,
                nodes: (0, normalize_1.normalizeNodes)(simplex.nodes.map((node) => (node === oldId ? newId : node))),
            };
            this.simplices.delete(key);
            this.simplices.set((0, normalize_1.normalizeKey)(updated.nodes), updated);
        }
        this.emitChange();
    }
    addSimplex(simplex) {
        const nodes = (0, normalize_1.uniqueNodes)(simplex.nodes);
        if (nodes.length < 2)
            return "";
        nodes.forEach((id) => {
            if (!this.nodes.has(id))
                this.setNode(id, { isVirtual: false });
        });
        const normalized = {
            ...simplex,
            nodes: (0, normalize_1.normalizeNodes)(nodes),
            weight: clampWeight(simplex.weight),
            autoGenerated: simplex.autoGenerated ?? false,
            userDefined: simplex.userDefined ?? !simplex.autoGenerated,
            colorKey: simplex.autoGenerated ? simplex.colorKey ?? "neutral" : simplex.colorKey ?? (0, hash_1.hashLabel)(simplex.label),
        };
        const key = (0, normalize_1.normalizeKey)(normalized.nodes);
        this.simplices.set(key, normalized);
        (0, faces_1.generateFaces)(this, normalized);
        this.emitChange();
        return key;
    }
    removeSimplex(key) {
        if (!this.simplices.delete(key))
            return;
        for (const [candidateKey, simplex] of [...this.simplices]) {
            if (!simplex.autoGenerated)
                continue;
            const hasParent = [...this.simplices.entries()].some(([otherKey, other]) => {
                if (otherKey === candidateKey)
                    return false;
                if (other.autoGenerated)
                    return false;
                return simplex.nodes.every((node) => other.nodes.includes(node));
            });
            if (!hasParent)
                this.simplices.delete(candidateKey);
        }
        this.emitChange();
    }
    replaceInferredSimplices(simplices) {
        this.batch(() => {
            for (const [key, simplex] of [...this.simplices]) {
                if (simplex.inferred) {
                    this.simplices.delete(key);
                }
            }
            simplices.forEach((simplex) => {
                simplex.nodes.forEach((id) => {
                    if (!this.nodes.has(id))
                        this.setNode(id, { isVirtual: false });
                });
                this.addSimplex(simplex);
            });
            this.emitChange();
        });
    }
    replaceSourceSimplices(sourcePath, simplices) {
        this.batch(() => {
            for (const [key, simplex] of [...this.simplices]) {
                if (simplex.sourcePath === sourcePath && !simplex.autoGenerated) {
                    this.simplices.delete(key);
                }
            }
            simplices.forEach((simplex) => {
                simplex.nodes.forEach((id) => {
                    if (!this.nodes.has(id))
                        this.setNode(id, { isVirtual: true });
                });
                this.addSimplex({ ...simplex, sourcePath });
            });
            this.emitChange();
        });
    }
    updateMetadata(key, meta) {
        const simplex = this.simplices.get(key);
        if (!simplex)
            return;
        const updated = { ...simplex, ...meta };
        if (meta.label !== undefined)
            updated.colorKey = simplex.autoGenerated ? "neutral" : (0, hash_1.hashLabel)(meta.label);
        if (meta.weight !== undefined)
            updated.weight = clampWeight(meta.weight);
        this.simplices.set(key, updated);
        this.emitChange();
    }
    setPinnedState(nodeId, pinned, px, py) {
        const node = this.nodes.get(nodeId);
        if (!node)
            return;
        node.isPinned = pinned;
        if (px !== undefined)
            node.px = px;
        if (py !== undefined)
            node.py = py;
        this.emitChange();
    }
    getSimplicesForNode(id) {
        return [...this.simplices.values()].filter((simplex) => simplex.nodes.includes(id));
    }
    getNeighbors(id) {
        const neighbors = new Set();
        this.getSimplicesForNode(id).forEach((simplex) => {
            simplex.nodes.forEach((node) => {
                if (node !== id)
                    neighbors.add(node);
            });
        });
        return [...neighbors];
    }
    getSimplicesByDim(targetDim) {
        return [...this.simplices.values()].filter((simplex) => simplex.nodes.length - 1 === targetDim);
    }
    getAllNodes() {
        return [...this.nodes.values()];
    }
    getSimplex(key) {
        return this.simplices.get(key);
    }
    getAnalysisSummary() {
        const simplices = [...this.simplices.values()];
        const edgeSimplices = simplices.filter((simplex) => simplex.nodes.length === 2);
        const adjacency = new Map();
        const simplexCentrality = new Map();
        this.nodes.forEach((_, nodeId) => adjacency.set(nodeId, new Set()));
        this.nodes.forEach((_, nodeId) => simplexCentrality.set(nodeId, 0));
        edgeSimplices.forEach((simplex) => {
            const [a, b] = simplex.nodes;
            adjacency.get(a)?.add(b);
            adjacency.get(b)?.add(a);
        });
        simplices.forEach((simplex) => {
            simplex.nodes.forEach((nodeId) => {
                simplexCentrality.set(nodeId, (simplexCentrality.get(nodeId) ?? 0) + 1);
            });
        });
        let connectedComponents = 0;
        const visited = new Set();
        adjacency.forEach((_, nodeId) => {
            if (visited.has(nodeId))
                return;
            connectedComponents++;
            const stack = [nodeId];
            while (stack.length > 0) {
                const current = stack.pop();
                if (visited.has(current))
                    continue;
                visited.add(current);
                adjacency.get(current)?.forEach((neighbor) => {
                    if (!visited.has(neighbor))
                        stack.push(neighbor);
                });
            }
        });
        let maxDegreeNodeId = null;
        let maxDegree = -1;
        let degreeTotal = 0;
        adjacency.forEach((neighbors, nodeId) => {
            const degree = neighbors.size;
            degreeTotal += degree;
            if (degree > maxDegree) {
                maxDegree = degree;
                maxDegreeNodeId = nodeId;
            }
        });
        let maxSimplexCentralityNodeId = null;
        let maxSimplexCentrality = -1;
        let simplexCentralityTotal = 0;
        simplexCentrality.forEach((centrality, nodeId) => {
            simplexCentralityTotal += centrality;
            if (centrality > maxSimplexCentrality) {
                maxSimplexCentrality = centrality;
                maxSimplexCentralityNodeId = nodeId;
            }
        });
        const betti = (0, betti_1.computeBetti)(this, 2);
        const holeCount = betti.holes.length;
        return {
            nodeCount: this.nodes.size,
            simplexCount: simplices.length,
            edgeCount: edgeSimplices.length,
            clusterCount: simplices.filter((simplex) => simplex.nodes.length === 3).length,
            coreCount: simplices.filter((simplex) => simplex.nodes.length >= 4).length,
            inferredCount: simplices.filter((simplex) => simplex.inferred).length,
            suggestedCount: simplices.filter((simplex) => simplex.suggested).length,
            connectedComponents,
            averageDegree: this.nodes.size ? Number((degreeTotal / this.nodes.size).toFixed(2)) : 0,
            maxDegreeNodeId,
            maxDegree: Math.max(0, maxDegree),
            maxSimplexCentralityNodeId,
            maxSimplexCentrality: Math.max(0, maxSimplexCentrality),
            averageSimplexCentrality: this.nodes.size ? Number((simplexCentralityTotal / this.nodes.size).toFixed(2)) : 0,
            betti,
            holeCount,
        };
    }
}
exports.SimplicialModel = SimplicialModel;
function clampWeight(weight) {
    if (weight === undefined || Number.isNaN(weight))
        return 1;
    return Math.max(0.1, Math.min(1, weight));
}
