export type NodeID = string;
export type SimplexKey = string;

export const VIEW_TYPE_SIMPLICIAL = "simplicial-view";
export const VIEW_TYPE_SIMPLICIAL_PANEL = "simplicial-panel";
export const MAX_FACE_GEN_DIM = 4;
export const MAX_RENDERED_DIM = 3;
export const HOLD_REPULSION = 900;

export const COLOR_PALETTE = ["purple", "teal", "coral", "pink", "blue", "amber"] as const;
export type ColorKey = (typeof COLOR_PALETTE)[number] | "neutral";

export interface Simplex {
  nodes: NodeID[];
  weight?: number;
  label?: string;
  colorKey?: ColorKey;
  autoGenerated?: boolean;
  userDefined?: boolean;
  inferred?: boolean;
  sourcePath?: string;
  parentKey?: string;
  inferredSignals?: string[];
  dominantSignal?: string;
  confidence?: number;
  suggested?: boolean;
}

export interface SimplicialComplex {
  simplices: Map<SimplexKey, Simplex>;
}

export interface LayoutNode {
  id: NodeID;
  px: number;
  py: number;
  vx: number;
  vy: number;
  isVirtual: boolean;
  isPinned: boolean;
  displayAlpha: number;
}

export interface Rect {
  width: number;
  height: number;
}

export interface PinnedState {
  [nodeId: string]: { px: number; py: number };
}

export interface PluginSettings {
  persistenceMode: "source-note" | "central-file";
  centralFile: string;
  showEdges: boolean;
  showClusters: boolean;
  showCores: boolean;
  maxRenderedDim: number;
  noiseAmount: number;
  sleepThreshold: number;
  repulsionStrength: number;
  cohesionStrength: number;
  gravityStrength: number;
  dampingFactor: number;
  boundaryPadding: number;
  darkMode: "auto" | "force-light" | "force-dark";
  linkGraphBaseline: boolean;
  enableInferredEdges: boolean;
  inferenceThreshold: number;
  linkWeight: number;
  mutualLinkBonus: number;
  sharedTagWeight: number;
  titleOverlapWeight: number;
  contentOverlapWeight: number;
  sameFolderWeight: number;
  sameTopFolderWeight: number;
  showSuggestions: boolean;
  suggestionThreshold: number;
  commandSimplexSize: number;
  commandAutoOpenPanel: boolean;
  metadataHoverDelayMs: number;
  formalMode: boolean;
  sparseEdgeLength: number;
  sparseGravityBoost: number;
  labelDensity: number;
  pinnedNodes: PinnedState;
}

export interface FocusState {
  isActive: boolean;
  lockedNodeId: NodeID | null;
  hoveredNodeId: NodeID | null;
  hoveredSimplexKey: SimplexKey | null;
  activeNodeIds: Set<NodeID>;
  activeSimplexKeys: Set<SimplexKey>;
  involvesNode(nodeId: NodeID): boolean;
  involvesSimplex(simplex: Simplex, key?: SimplexKey): boolean;
}

export interface ParserContext {
  sourcePath: string;
}

export interface SimplexRecord {
  key: SimplexKey;
  simplex: Simplex;
}

export interface ParsedFileResult {
  nodeIds: Set<NodeID>;
  simplices: Simplex[];
}

export interface MetadataSelection {
  key: SimplexKey | null;
}

export interface WritebackTarget {
  sourcePath: string;
  simplexKey: SimplexKey;
}

export interface AnalysisSummary {
  nodeCount: number;
  simplexCount: number;
  edgeCount: number;
  clusterCount: number;
  coreCount: number;
  inferredCount: number;
  suggestedCount: number;
  connectedComponents: number;
  averageDegree: number;
  maxDegreeNodeId: NodeID | null;
  maxDegree: number;
}
