import type { Simplex } from "../../core/types";
import type { InferenceConfig, InferenceContext, RawGraph, NoteProfile } from "./types";
import { buildRawGraph, getEdgeStrength, getNeighborsAbove } from "./graph";
import { detectOpenTriads } from "./rules/open-triad";
import { scoreCandidate } from "./scorer";
import type { CandidateSimplex } from "./types";

export function runEmergentInference(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  const graph = buildRawGraph(contexts, config);
  const triads = detectOpenTriads(graph, config);
  const allCandidates = triads;

  const scored = allCandidates
    .map((c) => scoreCandidate(c, [...graph.nodes.values()], config))
    .filter((c) => c.insightScore >= config.insightThreshold && c.class !== 'folder-cluster')
    .sort((a, b) => b.insightScore - a.insightScore)
    .map((c) => ({
      nodes: c.nodes,
      weight: c.decayedWeight,
      label: c.label ?? undefined,
      source: c.source,
      sourcePath: undefined,
      autoGenerated: true,
      inferred: true,
      userDefined: false,
      suggested: c.source === 'suggested',
      colorKey: 'neutral' as const,
      confidence: c.insightScore,
      inferredSignals: [],
      dominantSignal: 'soft-cluster',
      // class is in type; we preserve via label where needed
    }));

  return scored;
}

export function inferSimplicesEmergentWithMode(
  contexts: InferenceContext[],
  config: InferenceConfig,
): Simplex[] {
  return runEmergentInference(contexts, config);
}
